ZVox = ZVox or {}

-- movement stuff
ZVOX_MC_LIKE_CONTROLS = false


-- Player default constants
ZVOX_DEFAULT_PLAYER_REACH = 5

ZVOX_PLAYER_MAX_VEL_LENGTH = 4.75
ZVOX_PLAYER_MAX_VEL_LENGTH_WATER = 2.5


ZVOX_PLAYER_SLOW_MUL_WATER = 2.5
ZVOX_PLAYER_SLOW_MUL = 6
ZVOX_PLAYER_SLOW_MUL_AIR = 1

ZVOX_PLAYER_SWIM_SPEED_MUL = 1.45 * ZVOX_PLAYER_SLOW_MUL

ZVOX_PLAYER_WALK_SPEED_MUL = 6 * ZVOX_PLAYER_SLOW_MUL
ZVOX_PLAYER_WALK_SPEED_MUL_AIR = 4 * ZVOX_PLAYER_SLOW_MUL

-- fly mode constants
ZVOX_PLAYER_SLOW_MUL_FLYING = 2
ZVOX_PLAYER_SLOW_MUL_FLYING_VERTICAL = 8


ZVOX_PLAYER_FLY_SPEED_MUL = 16 * ZVOX_PLAYER_SLOW_MUL_FLYING
ZVOX_PLAYER_FLY_SPEED_MUL_VERTICAL = 24 * ZVOX_PLAYER_SLOW_MUL_FLYING

ZVOX_PLAYER_MAX_VEL_LENGTH_FLY = 12


ZVOX_MOVEMENT_WALK = 1
ZVOX_MOVEMENT_NOCLIP = 2


-- States
ZVOX_STATE_MAINMENU = 1
ZVOX_STATE_LOADING = 2
ZVOX_STATE_INGAME = 3
ZVOX_STATE_ENDING = 4



-- Rendering
ZVOX_FILTERMODE = TEXFILTER.POINT
ZVOX_DO_AO = true
ZVOX_DO_TEXTURES = true

ZVOX_DO_PARTICLES = true
ZVOX_DO_PARTICLE_COLLISIONS = true
ZVOX_DO_PARTICLE_EXPENSIVE_COLLISIONS = true -- EXPENSIVE particle ""collisions""
ZVOX_MAX_PARTICLE_COUNT = 384


ZVOX_DO_SINGLE_PASS_GLASS = true -- true for faster rendering, single pass glass that has artifacts
ZVOX_DO_FRUSTRUM_CULLING = true -- pretty good to get better fps on gpu bound hardware
ZVOX_DO_ANIMATED_TEXTURES = true -- whether or not to do animated textures
ZVOX_DO_SMOOTH_CLOUDS = true -- do / don't do linear filtering on the clouds ONLY
ZVOX_DO_LENS_FLARE = false -- do lens flares i devved cause i was bored

-- Fun!
ZVOX_DO_LOWRES_VIEWPORT = false
ZVOX_DO_WIREFRAME = false


-- Interface
ZVOX_DO_UI_BLUR = true
ZVOX_DO_UI_FASTMODE = false
ZVOX_DO_UI_ESC_CLOSE = true
ZVOX_DO_UI_NEW_GEN_INVENTORY = true
ZVOX_DO_UI_SHADOWS = true
ZVOX_USE_LEGACY_FONT_RENDERING = false
ZVOX_DO_PAUSE_BLUR = true


-- Audio
ZVOX_AUDIO_SOUND_SCALE = 60
ZVOX_AUDIO_EAR_POS = Vector(0, 0, 50000)

ZVOX_MUSIC_VOLUME = 50
ZVOX_VEHICLE_VOLUME = 50


-- Perf
ZVOX_MAX_REMESH_PER_FRAME = 1 -- How many chunks to remesh / frame

ZVOX_REMESH_HURRY_THRESHOLD = 64 -- how many remeshes left to enter hurry mode
ZVOX_MAX_REMESH_PER_FRAME_HURRY = 8 -- old 16 mesher per frame when in hurry mode

-- misc
ZVOX_DO_MC_FOV_CALC = true
ZVOX_DO_SCREEN_SHAKE = true


-- DEV
ZVOX_DO_STATE_REFRESH_ON_LUA_REFRESH = true
ZVOX_DO_FRUSTRUM_CULLING_FREEZE = false
ZVOX_CLAMP_PLAYER_POS = true
ZVOX_DEBUGDRAW_COLLISIONS = false


--mothervox
UNOBTAINALUM_POS = Vector(7, 8, 3)

MV_PART_DRILL = 1
MV_PART_HULL = 2
MV_PART_ENGINE = 3
MV_PART_FUEL_TANK = 4
MV_PART_RADIATOR = 5
MV_PART_STORAGE_BAY = 6
MV_PART_SENSOR = 7

MV_PART_MAX = MV_PART_SENSOR


MV_CONSUMABLE_FUEL_TANK = 1
MV_CONSUMABLE_NANOBOTS = 2
MV_CONSUMABLE_DYNAMITE = 3
MV_CONSUMABLE_C4 = 4
MV_CONSUMABLE_QUANTUM_TELE = 5
MV_CONSUMABLE_MATTER_TRANSMITTER = 6

MV_CONSUMABLE_MAX = MV_CONSUMABLE_MATTER_TRANSMITTER



MV_COMMUNICATION_WELCOME = 1
MV_COMMUNICATION_900M = 2
MV_COMMUNICATION_800M = 4
MV_COMMUNICATION_600M = 8
MV_COMMUNICATION_400M = 16
MV_COMMUNICATION_200M = 32
MV_COMMUNICATION_50M = 64