ZVox = ZVox or {}
VOXELSTATE_TYPE_NONE = 0
VOXELSTATE_TYPE_ZROT = 1
VOXELSTATE_TYPE_LOGROT = 2
VOXELSTATE_TYPE_SLAB = 3

VOXELSTATE_ROTATION_X_PLUS = 0
VOXELSTATE_ROTATION_X_MINUS = 1
VOXELSTATE_ROTATION_Y_PLUS = 2
VOXELSTATE_ROTATION_Y_MINUS = 3

VOXELSTATE_LOGROT_Z = 0
VOXELSTATE_LOGROT_Y = 1
VOXELSTATE_LOGROT_X = 2


VOXELSTATE_SLAB_LOWER = 0
VOXELSTATE_SLAB_UPPER = 1