ZVox = ZVox or {}

ZVox.PushVoxelCategory(ZVOX_VOXELCATEGORY_ABSTRACT)
ZVox.SimpleVoxel("white_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("light_gray_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("gray_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("dark_gray_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("black_wool", ZVOX_MAT_CLOTH)

ZVox.SimpleVoxel("voidinium_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("red_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("brown_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("orange_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("yellow_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("light_green_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("green_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("blueish_green_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("cyan_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("light_blue_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("blue_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("indigo_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("violet_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("purple_wool", ZVOX_MAT_CLOTH)
ZVox.SimpleVoxel("pink_wool", ZVOX_MAT_CLOTH)
